destination: ./_site
exclude    : [ 'Rakefile', 'Gemfile', 'Gemfile.lock' ]
lsi:         false
port:        4000
pygments:    false
markdown:    kramdown
permalink:   date
kramdown:
  use_coderay: true
  coderay:
    coderay_line_numbers:
    coderay_css: class
